name: example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_waya: ^3.5.1
  flutter_curiosity: ^4.1.0
  permission_handler: ^10.2.0
  flutter_image_compress: ^1.1.3
  fl_assets_picker:
    path: ../

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true