name: fl_assets_picker
description: fl_assets_picker is used to take photos of the device assets selection and camera and record videos
version: 5.1.2
repository: https://github.com/Wayaer/fl_assets_picker/tree/main/fl_assets_picker

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  wechat_assets_picker: '>=9.5.1 <=11.0.0'
  wechat_camera_picker: '>=4.3.0 <=6.0.0'
  photo_manager: '>=2.4.0 <=4.0.0'
  extended_image: '>=8.3.0 <11.0.0'
  extended_image_library: '>=4.0.0 <8.0.0'

dev_dependencies:
  flutter_lints: ^5.0.0
