name: fl_assets_picker
description: fl_assets_picker is used to take photos of the device assets selection and camera and record videos
version: 3.0.0
repository: https://github.com/Wayaer/fl_assets_picker/tree/main/fl_assets_picker

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  wechat_assets_picker: ^9.0.1
  wechat_camera_picker: ^4.2.0
  photo_manager: ^3.0.0

dev_dependencies:
  flutter_lints: ^3.0.1
