name: fl_assets_picker
description: fl_assets_picker is used to take photos of the device assets selection and camera and record videos
version: 4.1.0
repository: https://github.com/Wayaer/fl_assets_picker/tree/main/fl_assets_picker

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  wechat_assets_picker: ^9.3.0
  wechat_camera_picker: ^4.3.2
  photo_manager: ^3.4.0

dev_dependencies:
  flutter_lints: ^5.0.0
