name: fl_image_picker
description: fl_image_picker is used to take photos of the device assets selection and camera and record videos
version: 1.1.1
repository: https://github.com/Wayaer/fl_image_picker.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.13.0'

dependencies:
  flutter:
    sdk: flutter
  fl_video: ^1.3.1
  image_picker: ^1.0.4
  image_picker_android: ^0.8.7+5
  image_picker_platform_interface: ^2.9.1
  extended_image: ^8.1.1
  mime: ^1.0.4

dev_dependencies:
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true