name: fl_image_picker
description: fl_image_picker is used to take photos of the device assets selection and camera and record videos
version: 2.1.0
repository: https://github.com/Wayaer/fl_assets_picker/tree/main/fl_image_picker

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  mime: ^2.0.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true